version: "2"
run:
  tests: true
  allow-parallel-runners: true
linters:
  enable:
    - bodyclose
    - gocritic
    - gosec
    - misspell
    - revive
  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      confidence: 0.8
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
