# golangci-lint configuration file

version: "2"

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
    - bodyclose
    - gocritic
    - gosec
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    revive:
      confidence: 0.8

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
